-- MySQL Script generated by MySQL Workbench
-- 10/28/17 21:43:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `tipo_usuario` INT NOT NULL,
  `usuario_final` INT NOT NULL,
  `usuario_organico` INT NOT NULL,
  PRIMARY KEY (`tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacion` (
  `publicacion` VARCHAR(60) NOT NULL,
  `usuario_id` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  `descripcion_breve` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `estado` INT NULL,
  `fecha` DATE NULL,
  `tipo_ayuda` INT NOT NULL,
  `comentarios` VARCHAR(65) NULL,
  `tipo_usuario` INT NULL,
  PRIMARY KEY (`publicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_de_usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `contrasenia` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `codpostal` INT NOT NULL,
  `telefono` INT NOT NULL,
  `imagen` INT NULL,
  `categoria` INT NULL,
  `tipo_usuario_tipo_usuario1` INT NOT NULL,
  `publicacion_publicacion1` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`usuario_id`, `tipo_usuario_tipo_usuario1`, `publicacion_publicacion1`),
  UNIQUE INDEX `password_UNIQUE` (`contrasenia` ASC),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_tipo_usuario1` ASC),
  INDEX `fk_usuarios_publicacion1_idx` (`publicacion_publicacion1` ASC),
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_tipo_usuario1`)
    REFERENCES `mydb`.`tipo_usuario` (`tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_publicacion1`
    FOREIGN KEY (`publicacion_publicacion1`)
    REFERENCES `mydb`.`publicacion` (`publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tengo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tengo` (
  `idtengo` INT NOT NULL,
  `publicacion` VARCHAR(60) NULL,
  `tipo_ayuda` INT NULL,
  `usuario_id` INT NULL,
  `publicacion_publicacion` VARCHAR(60) NOT NULL,
  `id_publicacion` INT NULL,
  `publicacion_publicacion1` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idtengo`, `publicacion_publicacion1`),
  INDEX `fk_tengo_publicacion1_idx` (`publicacion_publicacion1` ASC),
  CONSTRAINT `fk_tengo_publicacion1`
    FOREIGN KEY (`publicacion_publicacion1`)
    REFERENCES `mydb`.`publicacion` (`publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`necesito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`necesito` (
  `idnecesito` INT NOT NULL,
  `publicacion` VARCHAR(60) NULL,
  `categoria` INT NULL,
  `tipo_ayuda` INT NULL,
  `usuario_id` INT NULL,
  `publicacion_publicacion` VARCHAR(60) NOT NULL,
  `categoria_categoria` INT NOT NULL,
  `id_publicacion` INT NULL,
  `publicacion_publicacion1` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idnecesito`, `publicacion_publicacion1`),
  INDEX `fk_necesito_publicacion1_idx` (`publicacion_publicacion1` ASC),
  CONSTRAINT `fk_necesito_publicacion1`
    FOREIGN KEY (`publicacion_publicacion1`)
    REFERENCES `mydb`.`publicacion` (`publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
